version: '3.2'
services:
    apache:
        build: .
        container_name: php56
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        links:
            - db
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: php56_phpmyadmin
        links:
            - db
        ports:
            - 8080:80

    db:
        image: mysql:5.7
        container_name: php56_db
        volumes:
            - /var/lib/mysql
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mydb

   
